import 'package:flutter/material.dart';
import 'package:gen/gen.dart';

final class CustomColorScheme {
  CustomColorScheme._();

  static ColorScheme lightColorScheme = ColorScheme.fromSeed(
    seedColor: Colors.blue,
    primary: const Color(0xff415f91),
    surfaceTint: const Color(0xff415f91),
    onPrimary: const Color(0xffffffff),
    primaryContainer: const Color(0xffd6e3ff),
    onPrimaryContainer: const Color(0xff001b3e),
    secondary: const Color(0xff565f71),
    onSecondary: const Color(0xffffffff),
    secondaryContainer: const Color(0xffdae2f9),
    onSecondaryContainer: const Color(0xff131c2b),
    tertiary: const Color(0xff705575),
    onTertiary: const Color(0xffffffff),
    tertiaryContainer: const Color(0xfffad8fd),
    onTertiaryContainer: const Color(0xff28132e),
    error: ColorName.crimsonRed,
    onError: const Color(0xffffffff),
    errorContainer: const Color(0xffffdad6),
    onErrorContainer: const Color(0xff410002),
    surface: const Color(0xfff9f9ff),
    onSurface: const Color(0xff191c20),
    onSurfaceVariant: const Color(0xff44474e),
    outline: const Color(0xff74777f),
    outlineVariant: const Color(0xffc4c6d0),
    shadow: const Color(0xff000000),
    scrim: const Color(0xff000000),
    inverseSurface: const Color(0xff2e3036),
    inversePrimary: const Color(0xffaac7ff),
    primaryFixed: const Color(0xffd6e3ff),
    onPrimaryFixed: const Color(0xff001b3e),
    primaryFixedDim: const Color(0xffaac7ff),
    onPrimaryFixedVariant: const Color(0xff284777),
    secondaryFixed: const Color(0xffdae2f9),
    onSecondaryFixed: const Color(0xff131c2b),
    secondaryFixedDim: const Color(0xffbec6dc),
    onSecondaryFixedVariant: const Color(0xff3e4759),
    tertiaryFixed: const Color(0xfffad8fd),
    onTertiaryFixed: const Color(0xff28132e),
    tertiaryFixedDim: const Color(0xffddbce0),
    onTertiaryFixedVariant: const Color(0xff573e5c),
    surfaceDim: const Color(0xffd9d9e0),
    surfaceBright: const Color(0xfff9f9ff),
    surfaceContainerLowest: const Color(0xffffffff),
    surfaceContainerLow: const Color(0xfff3f3fa),
    surfaceContainer: const Color(0xffededf4),
    surfaceContainerHigh: const Color(0xffe7e8ee),
    surfaceContainerHighest: const Color(0xffe2e2e9),
  );

  static ColorScheme darkColorScheme = ColorScheme.fromSeed(
    seedColor: Colors.blue,
    brightness: Brightness.dark,
    primary: const Color(0xffaac7ff),
    surfaceTint: const Color(0xffaac7ff),
    onPrimary: const Color(0xff0a305f),
    primaryContainer: const Color(0xff284777),
    onPrimaryContainer: const Color(0xffd6e3ff),
    secondary: const Color(0xffbec6dc),
    onSecondary: const Color(0xff283141),
    secondaryContainer: const Color(0xff3e4759),
    onSecondaryContainer: const Color(0xffdae2f9),
    tertiary: const Color(0xffddbce0),
    onTertiary: const Color(0xff3f2844),
    tertiaryContainer: const Color(0xff573e5c),
    onTertiaryContainer: const Color(0xfffad8fd),
    error: const Color(0xffffb4ab),
    onError: const Color(0xff690005),
    errorContainer: const Color(0xff93000a),
    onErrorContainer: const Color(0xffffdad6),
    surface: const Color(0xff111318),
    onSurface: const Color(0xffe2e2e9),
    onSurfaceVariant: const Color(0xffc4c6d0),
    outline: const Color(0xff8e9099),
    outlineVariant: const Color(0xff44474e),
    shadow: const Color(0xff000000),
    scrim: const Color(0xff000000),
    inverseSurface: const Color(0xffe2e2e9),
    inversePrimary: const Color(0xff415f91),
    primaryFixed: const Color(0xffd6e3ff),
    onPrimaryFixed: const Color(0xff001b3e),
    primaryFixedDim: const Color(0xffaac7ff),
    onPrimaryFixedVariant: const Color(0xff284777),
    secondaryFixed: const Color(0xffdae2f9),
    onSecondaryFixed: const Color(0xff131c2b),
    secondaryFixedDim: const Color(0xffbec6dc),
    onSecondaryFixedVariant: const Color(0xff3e4759),
    tertiaryFixed: const Color(0xfffad8fd),
    onTertiaryFixed: const Color(0xff28132e),
    tertiaryFixedDim: const Color(0xffddbce0),
    onTertiaryFixedVariant: const Color(0xff573e5c),
    surfaceDim: const Color(0xff111318),
    surfaceBright: const Color(0xff37393e),
    surfaceContainerLowest: const Color(0xff0c0e13),
    surfaceContainerLow: const Color(0xff191c20),
    surfaceContainer: const Color(0xff1d2024),
    surfaceContainerHigh: const Color(0xff282a2f),
    surfaceContainerHighest: const Color(0xff33353a),
  );
}
